version: '3.7'

services:
  mongodb:
    image: mongo:3.4
    container_name: pickly_db
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 8

  node_app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pickly
    container_name: pickly
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      MONGODB_URI: mongodb://mongodb:27017/pickly
      NODE_ENV: production
      PORT: 3000
    ports:
      - "127.0.0.1:3000:3000"

    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL

volumes:
  mongodb_data: